version: "3.4"

services:
  meta-ads:
    restart: unless-stopped
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    image: meta-ads-extraction
    container_name: meta-ads-extraction
    networks:
      - scrapper-network
    environment:
      APP_ENV: prod
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      META_APP_ID: ${META_APP_ID}
      META_LONG_TOKEN: ${META_LONG_TOKEN}

networks:
  scrapper-network:
    name: scrapper-network
