version: "3.4"

services:
  mongodb:
    image: mongo:5
    restart: unless-stopped
    container_name: mongodb-kiwanas
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ["--auth"]
  meta-ads:
    restart: unless-stopped
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    image: meta-ads-extraction-prod
    container_name: meta-ads-extraction-prod
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      META_APP_ID: ${META_APP_ID}
      META_LONG_TOKEN: ${META_LONG_TOKEN}
