version: "3.4"

services:
  meta-ads:
    restart: unless-stopped
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    image: meta-ads-extraction-prod
    container_name: meta-ads-extraction-prod
    environment:
      META_LONG_TOKEN: ${META_LONG_TOKEN}
      SCRAPPER_ID: ${SCRAPPER_ID}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_CLUSTER: ${MONGO_CLUSTER}
      SCRAPPER_SINCE_DATE: ${SCRAPPER_SINCE_DATE}
      SCRAPPER_UNTIL_DATE: ${SCRAPPER_UNTIL_DATE}
      APP_ENV: "prod"
