version: "3.4"

services:
  meta-ads:
    restart: unless-stopped
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    image: meta-ads-extraction-prod
    container_name: meta-ads-extraction-prod
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_SERVER: ${MONGO_SERVER}
      META_APP_ID: ${META_APP_ID}
      META_LONG_TOKEN: ${META_LONG_TOKEN}
