version: "3.4"

services:
  meta-ads:
    restart: unless-stopped
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    image: meta-ads-extraction
    container_name: meta-ads-extraction
    networks:
      - scrapper-network
    environment:
      APP_ENV: prod
      MIN_LIMIT_ADS: ${MIN_LIMIT_ADS}
      MAX_LIMIT_ADS: ${MAX_LIMIT_ADS}
      AD_DELIVERY_DATE_MIN: ${AD_DELIVERY_DATE_MIN}
      AD_DELIVERY_DATE_MAX: ${AD_DELIVERY_DATE_MAX}
      PROXY_SERVER: ${PROXY_SERVER}

      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_HOST: ${MONGO_HOST}

      META_APP_ID: ${META_APP_ID}
      META_USERNAME: ${META_USERNAME}
      META_PASSWORD: ${META_PASSWORD}
      META_LONG_TOKEN: ${META_LONG_TOKEN}

networks:
  scrapper-network:
    name: scrapper-network
